export const SERENA_ENGINE_MANIFEST = Object.freeze({
  engine: 'serena' as const,
  packageName: 'serena-agent',
  version: '1.7.0',
  upstreamCommit: '949a27ef1e5fda1a6e7b561e777bcece345c6ffd',
  wheelSha256: '6dbf1459670d96fb0595f84932adef34260a6fe14ba5135b901fdb3c8c76e891',
  pythonVersion: '3.13',
  transport: 'stdio' as const,
  languageBackend: 'LSP' as const,
  context: 'desktop-app',
  modes: Object.freeze(['no-memories'] as const),
  expectedToolNames: Object.freeze([
    'activate_project',
    'create_text_file',
    'execute_shell_command',
    'find_declaration',
    'find_file',
    'find_implementations',
    'find_referencing_symbols',
    'find_symbol',
    'get_current_config',
    'get_diagnostics_for_file',
    'get_symbols_overview',
    'initial_instructions',
    'insert_after_symbol',
    'insert_before_symbol',
    'list_dir',
    'read_file',
    'rename_symbol',
    'replace_content',
    'replace_in_files',
    'replace_symbol_body',
    'safe_delete_symbol',
    'search_for_pattern',
  ] as const),
});

export type SerenaExpectedToolName = (typeof SERENA_ENGINE_MANIFEST.expectedToolNames)[number];
